name: ebook_reader_flutter
description: A simple Flutter eBook Reader app
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^30.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/
